web:
  image: 'gitlab/gitlab-ce:latest'
 # restart: always
  hostname: 'mats-gitlab'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://18.184.13.162'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '$GITLAB_HOME/config:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'
